# Generated by Django 6.0 on 2025-12-19 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Sobrenome')),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, verbose_name='Gênero')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Formato: (00) 00000-0000', max_length=15, verbose_name='Telefone')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=10, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(help_text='Sigla (ex: SP)', max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(help_text='00000-000', max_length=9, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Registro Funcional')),
                ('education_level', models.CharField(choices=[('GRADUACAO', 'Graduação'), ('ESPECIALIZACAO', 'Especialização'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=20, verbose_name='Nível de Formação')),
                ('degree', models.CharField(help_text='Ex: Licenciatura em Matemática', max_length=100, verbose_name='Formação')),
                ('subjects', models.CharField(help_text='Separe com vírgula', max_length=500, verbose_name='Disciplinas')),
                ('contract_type', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('TEMPORARIO', 'Temporário'), ('HORISTA', 'Horista')], max_length=20, verbose_name='Tipo de Contrato')),
                ('hire_date', models.DateField(verbose_name='Data de Contratação')),
                ('workload', models.IntegerField(default=40, verbose_name='Carga Horária Semanal')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('is_coordinator', models.BooleanField(default=False, verbose_name='É Coordenador?')),
                ('coordinator_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Coordenação')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='Foto')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='teachers/curriculums/', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['registration_number'],
            },
        ),
    ]
