# Generated by Django 6.0 on 2025-12-18 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Sobrenome')),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, verbose_name='Gênero')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(help_text='Formato: (00) 00000-0000', max_length=15, verbose_name='Telefone')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('address_number', models.CharField(max_length=10, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(help_text='Sigla (ex: SP)', max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(help_text='00000-000', max_length=9, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='ID do Funcionário')),
                ('department', models.CharField(choices=[('DIRECAO', 'Direção'), ('SECRETARIA', 'Secretaria'), ('FINANCEIRO', 'Financeiro'), ('RH', 'Recursos Humanos'), ('PEDAGOGICO', 'Pedagógico'), ('TI', 'Tecnologia da Informação'), ('MANUTENCAO', 'Manutenção'), ('LIMPEZA', 'Limpeza')], max_length=20, verbose_name='Departamento')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('hire_date', models.DateField(verbose_name='Data de Contratação')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('access_level', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Administrador')], default=1, verbose_name='Nível de Acesso')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='É Supervisor?')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'ordering': ['employee_id'],
            },
        ),
    ]
