# Generated by Django 6.0 on 2025-12-25 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Nome",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Sobrenome",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Formato: 000.000.000-00",
                        max_length=14,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "rg",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="RG"
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Data de Nascimento")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("O", "Outro"),
                            ("N", "Prefiro não informar"),
                        ],
                        max_length=1,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Formato: (00) 00000-0000",
                        max_length=15,
                        verbose_name="Telefone",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Endereço")),
                (
                    "address_number",
                    models.CharField(max_length=10, verbose_name="Número"),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "state",
                    models.CharField(
                        help_text="Sigla (ex: SP)", max_length=2, verbose_name="Estado"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        help_text="00000-000", max_length=9, verbose_name="CEP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "enrollment_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matrícula"
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("INFANTIL", "Educação Infantil"),
                            ("FUNDAMENTAL1", "Ensino Fundamental I"),
                            ("FUNDAMENTAL2", "Ensino Fundamental II"),
                            ("MEDIO", "Ensino Médio"),
                            ("SUPERIOR", "Ensino Superior"),
                        ],
                        max_length=20,
                        verbose_name="Nível de Ensino",
                    ),
                ),
                (
                    "specific_grade",
                    models.CharField(
                        choices=[
                            ("1ANO", "1º Ano"),
                            ("2ANO", "2º Ano"),
                            ("3ANO", "3º Ano"),
                            ("4ANO", "4º Ano"),
                            ("5ANO", "5º Ano"),
                            ("6ANO", "6º Ano"),
                            ("7ANO", "7º Ano"),
                            ("8ANO", "8º Ano"),
                            ("9ANO", "9º Ano"),
                            ("1MEDIO", "1º Ano EM"),
                            ("2MEDIO", "2º Ano EM"),
                            ("3MEDIO", "3º Ano EM"),
                        ],
                        max_length=20,
                        verbose_name="Série/Ano",
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("MATUTINO", "Matutino"),
                            ("VESPERTINO", "Vespertino"),
                            ("NOTURNO", "Noturno"),
                            ("INTEGRAL", "Integral"),
                        ],
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Matrícula"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Pai",
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome da Mãe",
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefone do Responsável",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="students/photos/",
                        verbose_name="Foto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudante",
                "verbose_name_plural": "Estudantes",
                "ordering": ["enrollment_number"],
            },
        ),
    ]
