# Generated by Django 6.0 on 2025-12-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Instituição"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nome Curto"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Institucional"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Formato: (00) 00000-0000",
                        max_length=20,
                        verbose_name="Telefone",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Endereço")),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2, verbose_name="UF")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Instituição",
                "verbose_name_plural": "Instituições",
            },
        ),
    ]
